version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "./docker/dockerfile-dev"
    ports:
      - "80:80"
      - "3001:443"
    networks:
      - local
    links:
      - db
#      - redis
    volumes:
      - .:/app
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - local
#  redis:
#    image: redis:latest
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    networks:
#      - local
#    volumes:
#      - ../data-volumes:/data/db
networks:
  local:
